apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.2.11
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: echo-smoke-combined-live-combined-20260727233000-echo-operzlwcs
      namespace: echo-smoke-combined-live-combined-20260727233000
      uid: 8cdb4a1f-e9fa-4f84-ada4-0160716b5351
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-27T15:00:47Z"
    creationTimestamp: "2026-07-27T15:00:20Z"
    generateName: echo-smoke-combined-live-combined-20260727233000-echo-operator-
    generation: 7
    labels:
      app.kubernetes.io/instance: echo-smoke-combined-live-combined-20260727233000
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: echo-operator
      app.kubernetes.io/version: 0.1.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: echo-operator-0.1.0
      kubernetes.io/service-name: echo-smoke-combined-live-combined-20260727233000-echo-operator
    name: echo-smoke-combined-live-combined-20260727233000-echo-operwn26g
    namespace: echo-smoke-combined-live-combined-20260727233000
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: echo-smoke-combined-live-combined-20260727233000-echo-operator
      uid: 34354971-0b8d-40d6-bd77-9ce39453fd7c
    resourceVersion: "2225542"
    uid: dea2a89d-f601-4b16-a243-6d45692cb6b1
  ports:
  - name: webhook
    port: 8443
    protocol: TCP
  - name: metrics
    port: 8080
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
