apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    creationTimestamp: "2026-07-23T07:36:15Z"
    generation: 1
    name: echo-operator.default.echo.example.com
    resourceVersion: "2185996"
    uid: 33ab0916-7106-469c-b717-9f3fab401877
  webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHVENDQWdHZ0F3SUJBZ0lVQnMzYmVsTmtpbWE3ZG1iT3IyYitsQWdHekEwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0l6RWhNQjhHQTFVRUF3d1laV05vYnkxdmNHVnlZWFJ2Y2lCM1pXSm9iMjlySUVOQk1CNFhEVEkyTURjeQpNekEzTVRjeE0xb1hEVEkzTURjeU16QTNNVGN4TTFvd0l6RWhNQjhHQTFVRUF3d1laV05vYnkxdmNHVnlZWFJ2CmNpQjNaV0pvYjI5cklFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW5pQVYKUlBobVBRZjRERjBYaXJhMkErWGp4VDBubVBIY091OURycWZHbWErelY4MHdlbmFXMWtBK1F0OUdsYmVKYWFRdQpBb0FHYjdaUk5XY3JzQllhQ2o4eEtvdWI3dWRac2FSN0ZkdlZzTDVSL3RRSVh4elp2SFUxMEpnaHdQbjVPNW5wCmNpc0tPSGFyMXpDYXZWSHdmSTV5NHpIWTBmWFRCaFAvRGE3MmtxOWNSTGplU2JMUHRtN3g0SmtkMmphbC9kYjIKQlYycVdCSEJ1Rndlem5qTWJHVXVtaXFFRzZvb0ZJNHZTM3pnN3doVE1sQmhOK2h2eS9UMXVGcisvVzdaQ3VIYQpyM2ZXa1JDbGlGSVRuclJVRTY0MWZoQ05kemo0QldUQVYrZk1aaCtnVXNpd2o4ZFFvc2Z2VFhJNk92OHJRck1FClpyLzQ3UlZsQmV4UXZ0UjQ3d0lEQVFBQm8wVXdRekFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUE0R0ExVWQKRHdFQi93UUVBd0lCQmpBZEJnTlZIUTRFRmdRVUVLVTc1bTJMNFlYOTk4djNna3BNdlJMejkzd3dEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUk1SWlQQlhNbHUrS2I2MkhRd01KTWFsMXJzbWxzTUptS0FGSmJMVWpVNHE5bFNzCjdwbWo2SS9ZZUZQOE1yRmlhT0F3dlZJZ1p4a0dnYkEwQ3lva2JXTXp5Vk9iS1E5UjhpbG5KOVdySzluNEdacmkKMmxnaFhlSWZ2ZXhDTmRsOCtKbFpTVzFsUmxKaCtyMDNIUExreHpsUTZ4UnZTNE1RbjRNd3djYTgwTkhxZ1c4TgpSWEYxbWNINEhzTnBhNUExQWZWWUZGQ1B1WTRoL05WRnQwVnozMDhXQ2xPZUpWRVVha09TMnpwZ0VQcGhOUUhGCkZoaTVnRkNzQWkwZkY5OXQwYzNqU1N2L3kzRXlHUjNTSFhPd0ZkMlhnTjh4VDFNMXhsdVhQOUkzeFhMdG5mT0MKTzhhcDBzY212aE9DZGNCeWhRekN5Tlo1dUFQQWRyeWVXaE1kSGNjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: echo-operator
        namespace: default
        path: /validate/echo.example.com
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: echo-operator.default.echo.example.com
    namespaceSelector: {}
    objectSelector: {}
    rules:
    - apiGroups:
      - example.com
      apiVersions:
      - v1alpha1
      - v1alpha2
      operations:
      - CREATE
      - UPDATE
      resources:
      - echoresources
      scope: Namespaced
    sideEffects: None
    timeoutSeconds: 10
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    creationTimestamp: "2026-07-27T15:34:16Z"
    generation: 1
    name: echo-operator.echo-smoke-combined-live-combined-20260727252000.echo.example.com
    resourceVersion: "2231488"
    uid: 6ed3698f-63ff-448d-a0b1-ef9030c83e8b
  webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURmRENDQW1TZ0F3SUJBZ0lWQU1JK0pFbXAxWDYvWGJkYWhjMklKKzhrcTFHUU1BMEdDU3FHU0liM0RRRUIKQ3dVQU1GUXhVakJRQmdOVkJBTU1TV1ZqYUc4dGMyMXZhMlV0WTI5dFltbHVaV1F0YkdsMlpTMWpiMjFpYVc1bApaQzB5TURJMk1EY3lOekkxTWpBd01DMWxZMmh2TFc5d1pYSmhkRzl5SUhkbFltaHZiMnNnUTBFd0hoY05Nall3Ck56STNNVFV6TkRFMVdoY05NamN3TnpJM01UVXpOREUxV2pCVU1WSXdVQVlEVlFRRERFbGxZMmh2TFhOdGIydGwKTFdOdmJXSnBibVZrTFd4cGRtVXRZMjl0WW1sdVpXUXRNakF5TmpBM01qY3lOVEl3TURBdFpXTm9ieTF2Y0dWeQpZWFJ2Y2lCM1pXSm9iMjlySUVOQk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnhFTzR2ekpDMEZRNUNxSm5YUkpFWkxzVUdGdXI4WXVmczBtcXo2dlF4Uks2NVNQeDZ2eW8wRWVpUXZLVmVML1YKMWV3Ry9KS002Sms4RTJjcnlwZHg1OW1vZUVhekNTdDNvaHo1cU1hWENrU1p3S0NxRWJtMENUSTBGYkFEbTkxSgphN0FNZ2FxMytWRC96WHFVS0hocE1SeXk5VUoxUjc4M3QyVThqRVpRQWxDcUtscFJSRm9nbUM2a0hmVzNzVEZrCmZ6U0tCSUt5VHlxNks0cENncFM1UHZ0bnY2T29RVXpFNlJYU2JQOGRmZXlVTkgvdzViM1h6QUpjcTdtNzZUbDkKUEY2Rlhsd3BQdXFUQzcvQmY3MHlKdVBQR25ncUVmNzlXQXJXRklTdnVkQkgzWlNaVXJTQnUzbk55cmlDMHZ1bgpiNXZvL1d6R3NCNHNGaUVRRFZMRk5RSURBUUFCbzBVd1F6QVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQTRHCkExVWREd0VCL3dRRUF3SUJCakFkQmdOVkhRNEVGZ1FVNEo4ajRoQWtOcGNrd1dwNUM4MTMxUm9TbnJJd0RRWUoKS29aSWh2Y05BUUVMQlFBRGdnRUJBRWlPL2Zndy9kdEdRcUtYUldPRVlLNTFkRTJ5a0QrN1RHSVM0YTNHSjhHdAp4dnJNQWpwTk1NakduaWNpNDJmaTJlWmhnQ203UmJyR0w2NFhodExpUlJQenRxOXVTUU5jam1PeXZMQkQvMHNOCnJtVjc4QlBVRGxyRnA1WXJUSVlycnlMUGs5ZmlQVkgxSFNOMjdlV3hrZ3pkSHN4VWFlM0ZLSFc4ZGVNOThucm8KTlJxL2hwaUNpODZGZUZTRTdLQUdJS1N2eDMyVWtKQ1hsalEzSStreHVVRDB1SlkzUmw1empFU2tmSHhoQzR0SwpqTitMSkZVSW5zdi9xM1JSVkZrWWtSNTA3NkIxT3JESmkrZ1VGTm9KNzJya0tjNXh1U2c4TkJxcWNTc1NoaFAvCkw0YUUwN2dtNmI5NFh2K2kwK2JlSng0cndscmRyNnFBbjd6ajN0MEpsMzg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: echo-smoke-combined-live-combined-20260727252000-echo-operator
        namespace: echo-smoke-combined-live-combined-20260727252000
        path: /validate/echo.example.com
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: echo-operator.echo-smoke-combined-live-combined-20260727252000.echo.example.com
    namespaceSelector: {}
    objectSelector: {}
    rules:
    - apiGroups:
      - example.com
      apiVersions:
      - v1alpha1
      - v1alpha2
      operations:
      - CREATE
      - UPDATE
      resources:
      - echoresources
      scope: Namespaced
    sideEffects: None
    timeoutSeconds: 10
kind: List
metadata:
  resourceVersion: ""
