apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.2.31
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: echo-smoke-combined-live-combined-20260727250000-echo-opertgtqf
      namespace: echo-smoke-combined-live-combined-20260727250000
      uid: c4702548-383a-4ef2-a32b-e3744303f151
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-27T15:29:30Z"
    creationTimestamp: "2026-07-27T15:29:05Z"
    generateName: echo-smoke-combined-live-combined-20260727250000-echo-operator-
    generation: 7
    labels:
      app.kubernetes.io/instance: echo-smoke-combined-live-combined-20260727250000
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: echo-operator
      app.kubernetes.io/version: 0.1.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: echo-operator-0.1.0
      kubernetes.io/service-name: echo-smoke-combined-live-combined-20260727250000-echo-operator
    name: echo-smoke-combined-live-combined-20260727250000-echo-operh9pzj
    namespace: echo-smoke-combined-live-combined-20260727250000
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: echo-smoke-combined-live-combined-20260727250000-echo-operator
      uid: 602dc990-831a-45c0-aa80-e698aaf9ee83
    resourceVersion: "2230219"
    uid: acd92a16-1bb0-43be-a7f4-ea8c8142e1bf
  ports:
  - name: webhook
    port: 8443
    protocol: TCP
  - name: metrics
    port: 8080
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
