apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: "2026-07-27T16:03:59Z"
  generation: 1
  name: echo-operator.echo-smoke-split-live-split-20260728002000.echo.example.com
  resourceVersion: "2237477"
  uid: 5548a64f-2624-4835-bde0-9590061fc2b0
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVVkVmbXZOWjNPNk56dFR0M2N2VEZ2K3cyTEVnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dERVdNQlFHQTFVRUF3d05aV05vYnkxemJXOXJaUzFqWVRBZUZ3MHlOakEzTWpjeE5qQXpOVFZhRncweQpOakEzTWpneE5qQXpOVFZhTUJneEZqQVVCZ05WQkFNTURXVmphRzh0YzIxdmEyVXRZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURFWmQvanJMWGpRMlowOGVJMTd3WVFsSm1rajJNTk5FTjAKYjVEMzN6Yi9VLzBMWjlEUnNndWhmT01vMjZldFBYRmY3OWRFK2FQbEFnYnNsME9KdkZ3UmxHNG5Wak52TVQ2WQpNZ2hpa0pmZ0dabWdqZzdGeGtNSk1ZNlQrWXRCNnhSb1BOWDNMSXpQRDV1MFJiVTZ6SFVJWE9Pck01VUVqUUZ4ClNUMm1ENkkremR2VStId3o5aENac3J2VlhtL1RkazZ2MlVSV3I2Q09CeTVLZ2YzdlB0TGJnemk4RWNBSDlYZGYKS2dROWkxeFkwdTduc2FqUWEzbmxpSE8rZ2NrTThVY2NTQ2hJZ0ZCWUJ2eml2anN4SGYzaTV5QUcrYk1IZHpJVgpNb01DTmVIcEdYSVU0NWVZUGhnamxVd29BMGw5R1p5UjFKWEFGMnlIemtsRTVvRVkybk9YQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCU2JLdy9oeURucHBOR2tnZm83VzdoeHNhSW9RVEFmQmdOVkhTTUVHREFXZ0JTYkt3L2gKeURucHBOR2tnZm83VzdoeHNhSW9RVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCSGU3SVFibGhVTUJYM2FUNDZpemR3eVV5VzZBVHp5WlRCMEFSaGFSVmdHQUFMOTVLTEJwQnA3cmhDCkg0b2d1MUxLY2FVd3RWczdSUmoxVVVYQWZRT3RRaDB5ZVpudnpiN1lvakZvSDlEQVBJQ3dEVHNqS000TjJBSEwKUEM3L3k3d0VUVXJtZ2VGRW1MUWxYQjBXOExmUkh6L1lGeGpiM3RValV0N21SVERZSUZoRk1LeFFyYUFJanpGVgpZaWliOER2VDNjbnB6cE9wa3RsNnRUNHRKYk5nQllyMi9rczJpRXVuUDVwQUR4clZvQ2xOS01OY3NWcEp4NElmCjA4aUhFYktNa2RjNFVWVGIwWU0rUDRsMkp0NjJ5N3lRdEUrUDJxZEU0RDc3Yk1hL1FSOTZpUXREYlk3cU9paVIKVlZ1Rmt2Unc4U1UyMml0YVNUaTk5QnQ0ZXVXdAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: echo-smoke-split-live-split-20260728002000-echo-operator
      namespace: echo-smoke-split-live-split-20260728002000
      path: /mutate/echo.example.com
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: echo-operator.echo-smoke-split-live-split-20260728002000.echo.example.com
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - example.com
    apiVersions:
    - v1alpha1
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - echoresources
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10
