apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: "2026-07-27T16:11:52Z"
  generation: 1
  name: echo-operator.echo-smoke-split-live-split-20260728004000.echo.example.com
  resourceVersion: "2239189"
  uid: 06579c3d-a9d3-4794-a99e-ca1158f3b6d9
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVRy92WCtKTXFOWWljV0c2bEpBcWNKczZQR3Njd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dERVdNQlFHQTFVRUF3d05aV05vYnkxemJXOXJaUzFqWVRBZUZ3MHlOakEzTWpjeE5qRXhORGhhRncweQpOakEzTWpneE5qRXhORGhhTUJneEZqQVVCZ05WQkFNTURXVmphRzh0YzIxdmEyVXRZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNLN1dCUlkrYlJYNWx0SVNlRTFrcFJPeUduTDhGdFpUTDYKNlQxZjlvdUNFQWxsRU80VTNDWHJ0UE9mdml6TitWQkVvTlJrakJzczlCMGtyVG1uRVZ5Z3NkaUxDSzFCZlFkeQpUZ0dDb1VxNldBZVpaWDdHTDV5NkVwYVNuT0lnd0E3dXQzKzU4V2YveWlMSUQrNFc4Y3MyQTFHKzhNV0Z6UDJOCmpZUGMxUk5qM05kbmlBWjBkRzB5eUU1UVNPQ29VbzNuNm0wVTJ1YUdiazJxN0p3U21PblBRS0dEbFdwcm1TUE8KY3hsRmFYb0oycUpSam1rd0dXdldVVFRsdkhPT3Qvd0dLOVlqaGI3VUVwODl2d0QwUlEwTCt5bDhTVThCZ0VQbQpaMVZDNmRqamlyQzhwL05RT2tpTDdYcHJWVmM0ZWREUXIwTUlQKzFHMXovTWZaSzhHelM1QWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCUUFYNG9od2NyK09iRUR1Y1o0UUQzdExnelZ3akFmQmdOVkhTTUVHREFXZ0JRQVg0b2gKd2NyK09iRUR1Y1o0UUQzdExnelZ3akFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCZDlvYUZhdWNmUGs4VFJ4V1FaSlZpdTBJOWVzU3pQbTdiTFIrTjJJV0RGQ01ySXo3UUxReWhSaTMrCjF5Y0hHcjFOQVQwd1ZCZHBVd2FiNFpvN3BudVk2c0w0NFlrRzY2STRiakdnNDRNRXYyOCtNcm8rUkM1alZmeE0KcXgyOWNicVA0Vk1mZGkrMnBMdksxdXRISWEydDJrNU9MN3NibTg5MDVabFZCYXZWd29oQ3p5bjV1ZVVhTW9MSwpnMDNlRk8yY1B4Q29OTmQrSEc1ZVB6TTNtbzFZbStRbDhuR0V1TktmeURlUnlOWnphQStNOHd3a2VhRi9ra0wxCkRpa0pMLytSWVp2c2NITGdPS2doaFlNcWZpOVlCSlRTRFV1M1llV0dvMW52WTZ3Szk1QnpFTjk0dUVRSmI4bUMKdFlrN2Z4ZlpQbnZmTUJuSFJaclh4bEFQWGtVdQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: echo-smoke-split-live-split-20260728004000-echo-operator
      namespace: echo-smoke-split-live-split-20260728004000
      path: /validate/echo.example.com
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: echo-operator.echo-smoke-split-live-split-20260728004000.echo.example.com
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - example.com
    apiVersions:
    - v1alpha1
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - echoresources
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10
