apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.2.99
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: echo-smoke-split-live-split-20260728004000-echo-oper-webhocdg7k
      namespace: echo-smoke-split-live-split-20260728004000
      uid: d108ddf2-bdf7-4278-931e-dfc1b8fe00c6
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-27T16:12:01Z"
    creationTimestamp: "2026-07-27T16:11:49Z"
    generateName: echo-smoke-split-live-split-20260728004000-echo-operator-
    generation: 3
    labels:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: echo-smoke-split-live-split-20260728004000
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: echo-operator
      app.kubernetes.io/version: 0.1.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: echo-operator-0.1.0
      kubernetes.io/service-name: echo-smoke-split-live-split-20260728004000-echo-operator
    name: echo-smoke-split-live-split-20260728004000-echo-operator-srmhr
    namespace: echo-smoke-split-live-split-20260728004000
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: echo-smoke-split-live-split-20260728004000-echo-operator
      uid: a1d0e487-9387-4cc2-ab94-f2fbc5e7f406
    resourceVersion: "2239210"
    uid: 913470ee-5759-4fe2-8f00-dbdf1ce2921f
  ports:
  - name: webhook
    port: 8443
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
