package com.example.echooperator;

import com.huawei.dcs.modelengine.operator.framework.Operator;
import com.huawei.dcs.modelengine.operator.framework.webhook.registration.WebhookRegistrationConfig;
import com.huawei.dcs.modelengine.operator.framework.webhook.registration.WebhookSelfRegistration;
import io.fabric8.kubernetes.api.model.Secret;
import io.fabric8.kubernetes.api.model.SecretList;
import io.fabric8.kubernetes.api.model.admissionregistration.v1.RuleWithOperations;
import io.fabric8.kubernetes.api.model.admissionregistration.v1.MutatingWebhook;
import io.fabric8.kubernetes.api.model.admissionregistration.v1.MutatingWebhookConfiguration;
import io.fabric8.kubernetes.api.model.admissionregistration.v1.MutatingWebhookConfigurationList;
import io.fabric8.kubernetes.api.model.admissionregistration.v1.ValidatingWebhook;
import io.fabric8.kubernetes.api.model.admissionregistration.v1.ValidatingWebhookConfiguration;
import io.fabric8.kubernetes.api.model.admissionregistration.v1.ValidatingWebhookConfigurationList;
import io.fabric8.kubernetes.client.AdmissionRegistrationAPIGroupDSL;
import io.fabric8.kubernetes.client.KubernetesClient;
import io.fabric8.kubernetes.client.V1AdmissionRegistrationAPIGroupDSL;
import io.fabric8.kubernetes.client.dsl.MixedOperation;
import io.fabric8.kubernetes.client.dsl.NonNamespaceOperation;
import io.fabric8.kubernetes.client.dsl.Resource;
import io.fabric8.kubernetes.client.utils.KubernetesSerialization;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.ArgumentCaptor;
import org.mockito.MockedConstruction;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class EchoOperatorMainWiringTest {

    @TempDir
    Path tempDir;

    @Test
    void disabledWebhooksSkipComponentsCleanUpStaleRegistrationsAndStop() throws IOException, InterruptedException {
        ClientFixture fixture = client();
        EchoOperatorMain.OperatorConfig config = config("watched-ns", "pod-ns", false, false,
                "configured-service", "service-ns", tempDir.resolve("unused-certs"),
                tempDir.resolve("fallback-ca.crt"));

        try (MockedConstruction<Operator> operators = mockOperatorConstruction();
                MockedConstruction<WebhookSelfRegistration> registrations =
                        org.mockito.Mockito.mockConstruction(WebhookSelfRegistration.class)) {
            EchoOperatorMain main = EchoOperatorMain.create(fixture.client(), config);

            assertNull(main.webhookServer());
            assertNull(main.admissionHandler());
            assertNull(main.conversionHandler());
            assertNull(main.webhookSelfRegistration());

            main.start();
            HttpResponse<Void> healthResponse = HttpClient.newHttpClient().send(HttpRequest.newBuilder(
                    URI.create("http://localhost:" + main.metricsHealthServer().address().getPort() + "/healthz"))
                    .GET().build(),
                    HttpResponse.BodyHandlers.discarding());
            assertEquals(200, healthResponse.statusCode());
            WebhookSelfRegistration cleanup = registrations.constructed().getFirst();
            verify(cleanup).unregisterAdmissionWebhooks("echo-operator.watched-ns",
                    List.of("echo.example.com"), List.of("echo.example.com"));
            verify(operators.constructed().getFirst()).start();
            assertTrue(main.metricsHealthServer().address() instanceof InetSocketAddress);

            main.stop();
            verify(operators.constructed().getFirst()).stop();
        }
    }

    @Test
    void autoGeneratedCertificatesUsePodNamespaceAndStartPatchesConfiguredConversionService() throws IOException {
        ClientFixture fixture = client();
        Path certDirectory = tempDir.resolve("generated-certs");
        EchoOperatorMain.OperatorConfig config = config("watched-ns", "pod-ns", true, true,
                "configured-service", "service-ns", certDirectory, tempDir.resolve("fallback-ca.crt"));

        try (MockedConstruction<Operator> operators = mockOperatorConstruction();
                MockedConstruction<WebhookSelfRegistration> registrations =
                        org.mockito.Mockito.mockConstruction(WebhookSelfRegistration.class)) {
            EchoOperatorMain main = EchoOperatorMain.create(fixture.client(), config);

            assertTrue(Files.exists(certDirectory.resolve("ca.crt")));
            assertTrue(Files.exists(certDirectory.resolve("tls.crt")));
            assertTrue(Files.exists(certDirectory.resolve("tls.key")));

            ArgumentCaptor<Secret> secretCaptor = ArgumentCaptor.forClass(Secret.class);
            verify(fixture.namespacedSecrets()).resource(secretCaptor.capture());
            assertEquals("pod-ns", secretCaptor.getValue().getMetadata().getNamespace());

            main.start();
            WebhookSelfRegistration registration = registrations.constructed().getFirst();
            ArgumentCaptor<Path> caPath = ArgumentCaptor.forClass(Path.class);
            verify(registration).patchConversionWebhookClientConfig(eq("echoresources.example.com"), caPath.capture(),
                    eq("configured-service"), eq("service-ns"), eq(9443));
            assertTrue(caPath.getValue().startsWith(certDirectory));
            verify(operators.constructed().getFirst()).start();

            main.stop();
        }
    }

    @Test
    void admissionRegistrationUsesConfiguredServiceIdentityWithStableBaseName() throws IOException {
        ClientFixture firstFixture = client();
        ClientFixture secondFixture = client();
        Path firstCaPath = tempDir.resolve("first-ca.crt");
        Path secondCaPath = tempDir.resolve("second-ca.crt");
        Files.writeString(firstCaPath, "first-ca");
        Files.writeString(secondCaPath, "second-ca");
        EchoOperatorMain.OperatorConfig firstConfig = config("watched-ns", "pod-ns", true, true,
                "first-service", "first-service-ns", tempDir.resolve("first-certs"), firstCaPath);
        EchoOperatorMain.OperatorConfig secondConfig = config("watched-ns", "pod-ns", true, true,
                "second-service", "second-service-ns", tempDir.resolve("second-certs"), secondCaPath);
        List<WebhookRegistrationConfig> registrationConfigs = new ArrayList<>();
        List<EchoOperatorMain> mains = new ArrayList<>();

        try (MockedConstruction<WebhookSelfRegistration> registrations = org.mockito.Mockito.mockConstruction(
                WebhookSelfRegistration.class, (mock, context) -> registrationConfigs.add(
                        (WebhookRegistrationConfig) context.arguments().get(1)))) {
            mains.add(EchoOperatorMain.create(firstFixture.client(), firstConfig));
            mains.add(EchoOperatorMain.create(secondFixture.client(), secondConfig));

            assertEquals(2, registrationConfigs.size());
            assertRegistrationConfig(registrationConfigs.get(0), firstConfig);
            assertRegistrationConfig(registrationConfigs.get(1), secondConfig);
        }

        new WebhookSelfRegistration(firstFixture.client(), registrationConfigs.get(0))
                .register(mains.get(0).admissionHandler());
        new WebhookSelfRegistration(secondFixture.client(), registrationConfigs.get(1))
                .register(mains.get(1).admissionHandler());
        assertAdmissionRegistration(firstFixture, "first-service", "first-service-ns");
        assertAdmissionRegistration(secondFixture, "second-service", "second-service-ns");

        mains.get(0).stop();
        mains.get(1).stop();
    }

    private void assertRegistrationConfig(WebhookRegistrationConfig registrationConfig,
            EchoOperatorMain.OperatorConfig config) {
        assertEquals(config.webhookServiceName(), registrationConfig.serviceName());
        assertEquals(config.webhookServiceNamespace(), registrationConfig.serviceNamespace());
        assertEquals("echo-operator." + config.operatorNamespace(), registrationConfig.baseName());
        RuleWithOperations rule = registrationConfig.rules().getFirst();
        assertEquals(List.of("example.com"), rule.getApiGroups());
        assertEquals(List.of("v1alpha1", "v1alpha2"), rule.getApiVersions());
        assertEquals(List.of("CREATE", "UPDATE"), rule.getOperations());
        assertEquals(List.of("echoresources"), rule.getResources());
        assertEquals("Namespaced", rule.getScope());
    }

    private void assertAdmissionRegistration(ClientFixture fixture, String serviceName, String serviceNamespace) {
        ArgumentCaptor<ValidatingWebhookConfiguration> validatingCaptor = ArgumentCaptor.forClass(
                ValidatingWebhookConfiguration.class);
        verify(fixture.validating()).resource(validatingCaptor.capture());
        verify(fixture.validatingResource()).createOrReplace();
        ValidatingWebhookConfiguration validating = validatingCaptor.getValue();
        ValidatingWebhook validatingWebhook = validating.getWebhooks().getFirst();
        assertEquals("echo-operator.watched-ns.echo.example.com", validating.getMetadata().getName());
        assertEquals("echo-operator.watched-ns.echo.example.com", validatingWebhook.getName());
        assertEquals(serviceName, validatingWebhook.getClientConfig().getService().getName());
        assertEquals(serviceNamespace, validatingWebhook.getClientConfig().getService().getNamespace());
        assertEquals(9443, validatingWebhook.getClientConfig().getService().getPort());

        ArgumentCaptor<MutatingWebhookConfiguration> mutatingCaptor = ArgumentCaptor.forClass(
                MutatingWebhookConfiguration.class);
        verify(fixture.mutating()).resource(mutatingCaptor.capture());
        verify(fixture.mutatingResource()).createOrReplace();
        MutatingWebhookConfiguration mutating = mutatingCaptor.getValue();
        MutatingWebhook mutatingWebhook = mutating.getWebhooks().getFirst();
        assertEquals("echo-operator.watched-ns.echo.example.com", mutating.getMetadata().getName());
        assertEquals("echo-operator.watched-ns.echo.example.com", mutatingWebhook.getName());
        assertEquals(serviceName, mutatingWebhook.getClientConfig().getService().getName());
        assertEquals(serviceNamespace, mutatingWebhook.getClientConfig().getService().getNamespace());
        assertEquals(9443, mutatingWebhook.getClientConfig().getService().getPort());
    }

    private EchoOperatorMain.OperatorConfig config(String operatorNamespace, String operatorPodNamespace,
            boolean webhookEnabled, boolean autoGenerate, String serviceName, String serviceNamespace,
            Path certDirectory, Path caBundlePath) {
        return new EchoOperatorMain.OperatorConfig(operatorNamespace, operatorPodNamespace, 0, false,
                operatorNamespace, "echo-operator-lock", caBundlePath, webhookEnabled, autoGenerate,
                "echo-operator-webhook-ca", serviceName, serviceNamespace, certDirectory, 0, 9443);
    }

    private MockedConstruction<Operator> mockOperatorConstruction() {
        return org.mockito.Mockito.mockConstruction(Operator.class,
                (operator, context) -> when(operator.withNamespace(anyString())).thenReturn(operator));
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private ClientFixture client() {
        KubernetesClient client = mock(KubernetesClient.class);
        MixedOperation<Secret, SecretList, Resource<Secret>> secrets = mock(MixedOperation.class);
        NonNamespaceOperation<Secret, SecretList, Resource<Secret>> namespacedSecrets = mock(NonNamespaceOperation.class);
        Resource<Secret> secretResource = mock(Resource.class);
        AdmissionRegistrationAPIGroupDSL admission = mock(AdmissionRegistrationAPIGroupDSL.class);
        V1AdmissionRegistrationAPIGroupDSL admissionV1 = mock(V1AdmissionRegistrationAPIGroupDSL.class);
        NonNamespaceOperation<ValidatingWebhookConfiguration, ValidatingWebhookConfigurationList,
                Resource<ValidatingWebhookConfiguration>> validating = mock(NonNamespaceOperation.class);
        Resource<ValidatingWebhookConfiguration> validatingResource = mock(Resource.class);
        NonNamespaceOperation<MutatingWebhookConfiguration, MutatingWebhookConfigurationList,
                Resource<MutatingWebhookConfiguration>> mutating = mock(NonNamespaceOperation.class);
        Resource<MutatingWebhookConfiguration> mutatingResource = mock(Resource.class);
        when(client.secrets()).thenReturn(secrets);
        when(secrets.inNamespace(anyString())).thenReturn(namespacedSecrets);
        when(namespacedSecrets.withName(anyString())).thenReturn(secretResource);
        when(namespacedSecrets.resource(any(Secret.class))).thenReturn(secretResource);
        when(secretResource.get()).thenReturn(null);
        when(client.admissionRegistration()).thenReturn(admission);
        when(admission.v1()).thenReturn(admissionV1);
        when(admissionV1.validatingWebhookConfigurations()).thenReturn(validating);
        when(validating.resource(any(ValidatingWebhookConfiguration.class))).thenReturn(validatingResource);
        when(admissionV1.mutatingWebhookConfigurations()).thenReturn(mutating);
        when(mutating.resource(any(MutatingWebhookConfiguration.class))).thenReturn(mutatingResource);
        when(client.getKubernetesSerialization()).thenReturn(new KubernetesSerialization());
        return new ClientFixture(client, namespacedSecrets, validating, validatingResource, mutating, mutatingResource);
    }

    private record ClientFixture(KubernetesClient client,
            NonNamespaceOperation<Secret, SecretList, Resource<Secret>> namespacedSecrets,
            NonNamespaceOperation<ValidatingWebhookConfiguration, ValidatingWebhookConfigurationList,
                    Resource<ValidatingWebhookConfiguration>> validating,
            Resource<ValidatingWebhookConfiguration> validatingResource,
            NonNamespaceOperation<MutatingWebhookConfiguration, MutatingWebhookConfigurationList,
                    Resource<MutatingWebhookConfiguration>> mutating,
            Resource<MutatingWebhookConfiguration> mutatingResource) {
    }
}
