{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "echo-operator.fullname" . }}
  labels:
    {{- include "echo-operator.labels" . | nindent 4 }}
rules:
{{- if .Values.webhook.enabled }}
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update", "patch"]
{{- else }}
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    resourceNames: [{{ printf "echo-operator.%s.echo.example.com" .Release.Namespace | quote }}]
    verbs: ["get", "delete"]
{{- end }}
{{- end }}
