{{- $mode := include "echo-operator.deploymentMode" . -}}
{{- if eq $mode "combined" }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "echo-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "echo-operator.labels" . | nindent 4 }}
{{- end }}
{{- else }}
{{- if .Values.controller.workload.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "echo-operator.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "echo-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- end }}
{{- if .Values.webhook.workload.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "echo-operator.webhookServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "echo-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
{{- end }}
{{- end }}
