apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.2.64
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: echo-smoke-combined-live-combined-20260727280000-echo-operdgjrl
      namespace: echo-smoke-combined-live-combined-20260727280000
      uid: 7b50db3f-3216-4368-92f2-5311914d4540
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-27T15:55:25Z"
    creationTimestamp: "2026-07-27T15:54:59Z"
    generateName: echo-smoke-combined-live-combined-20260727280000-echo-operator-
    generation: 7
    labels:
      app.kubernetes.io/instance: echo-smoke-combined-live-combined-20260727280000
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: echo-operator
      app.kubernetes.io/version: 0.1.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: echo-operator-0.1.0
      kubernetes.io/service-name: echo-smoke-combined-live-combined-20260727280000-echo-operator
    name: echo-smoke-combined-live-combined-20260727280000-echo-operl8ldk
    namespace: echo-smoke-combined-live-combined-20260727280000
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: echo-smoke-combined-live-combined-20260727280000-echo-operator
      uid: cf10e3b1-1a52-47a0-9fd3-98b8d8125d1b
    resourceVersion: "2235259"
    uid: 93b25822-754d-4d9b-adf6-60a25e20f34d
  ports:
  - name: webhook
    port: 8443
    protocol: TCP
  - name: metrics
    port: 8080
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
