apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1
  kind: MutatingWebhookConfiguration
  metadata:
    creationTimestamp: "2026-07-23T07:36:15Z"
    generation: 1
    name: echo-operator.default.echo.example.com
    resourceVersion: "2185997"
    uid: 501f930e-aff7-4eb4-83a6-be757bf9752b
  webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHVENDQWdHZ0F3SUJBZ0lVQnMzYmVsTmtpbWE3ZG1iT3IyYitsQWdHekEwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0l6RWhNQjhHQTFVRUF3d1laV05vYnkxdmNHVnlZWFJ2Y2lCM1pXSm9iMjlySUVOQk1CNFhEVEkyTURjeQpNekEzTVRjeE0xb1hEVEkzTURjeU16QTNNVGN4TTFvd0l6RWhNQjhHQTFVRUF3d1laV05vYnkxdmNHVnlZWFJ2CmNpQjNaV0pvYjI5cklFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW5pQVYKUlBobVBRZjRERjBYaXJhMkErWGp4VDBubVBIY091OURycWZHbWErelY4MHdlbmFXMWtBK1F0OUdsYmVKYWFRdQpBb0FHYjdaUk5XY3JzQllhQ2o4eEtvdWI3dWRac2FSN0ZkdlZzTDVSL3RRSVh4elp2SFUxMEpnaHdQbjVPNW5wCmNpc0tPSGFyMXpDYXZWSHdmSTV5NHpIWTBmWFRCaFAvRGE3MmtxOWNSTGplU2JMUHRtN3g0SmtkMmphbC9kYjIKQlYycVdCSEJ1Rndlem5qTWJHVXVtaXFFRzZvb0ZJNHZTM3pnN3doVE1sQmhOK2h2eS9UMXVGcisvVzdaQ3VIYQpyM2ZXa1JDbGlGSVRuclJVRTY0MWZoQ05kemo0QldUQVYrZk1aaCtnVXNpd2o4ZFFvc2Z2VFhJNk92OHJRck1FClpyLzQ3UlZsQmV4UXZ0UjQ3d0lEQVFBQm8wVXdRekFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUE0R0ExVWQKRHdFQi93UUVBd0lCQmpBZEJnTlZIUTRFRmdRVUVLVTc1bTJMNFlYOTk4djNna3BNdlJMejkzd3dEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUk1SWlQQlhNbHUrS2I2MkhRd01KTWFsMXJzbWxzTUptS0FGSmJMVWpVNHE5bFNzCjdwbWo2SS9ZZUZQOE1yRmlhT0F3dlZJZ1p4a0dnYkEwQ3lva2JXTXp5Vk9iS1E5UjhpbG5KOVdySzluNEdacmkKMmxnaFhlSWZ2ZXhDTmRsOCtKbFpTVzFsUmxKaCtyMDNIUExreHpsUTZ4UnZTNE1RbjRNd3djYTgwTkhxZ1c4TgpSWEYxbWNINEhzTnBhNUExQWZWWUZGQ1B1WTRoL05WRnQwVnozMDhXQ2xPZUpWRVVha09TMnpwZ0VQcGhOUUhGCkZoaTVnRkNzQWkwZkY5OXQwYzNqU1N2L3kzRXlHUjNTSFhPd0ZkMlhnTjh4VDFNMXhsdVhQOUkzeFhMdG5mT0MKTzhhcDBzY212aE9DZGNCeWhRekN5Tlo1dUFQQWRyeWVXaE1kSGNjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: echo-operator
        namespace: default
        path: /mutate/echo.example.com
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: echo-operator.default.echo.example.com
    namespaceSelector: {}
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - example.com
      apiVersions:
      - v1alpha1
      - v1alpha2
      operations:
      - CREATE
      - UPDATE
      resources:
      - echoresources
      scope: Namespaced
    sideEffects: None
    timeoutSeconds: 10
- apiVersion: admissionregistration.k8s.io/v1
  kind: MutatingWebhookConfiguration
  metadata:
    creationTimestamp: "2026-07-27T16:00:37Z"
    generation: 1
    name: echo-operator.echo-smoke-combined-live-combined-20260727290000.echo.example.com
    resourceVersion: "2236348"
    uid: a3af97a0-ed71-4780-bc5a-7d622c5e5b20
  webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lVSjFoekgxU0NjeEUxNnZxT01YK3ViZXoraUNVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1ZERlNNRkFHQTFVRUF3eEpaV05vYnkxemJXOXJaUzFqYjIxaWFXNWxaQzFzYVhabExXTnZiV0pwYm1WawpMVEl3TWpZd056STNNamt3TURBd0xXVmphRzh0YjNCbGNtRjBiM0lnZDJWaWFHOXZheUJEUVRBZUZ3MHlOakEzCk1qY3hOakF3TXpaYUZ3MHlOekEzTWpjeE5qQXdNelphTUZReFVqQlFCZ05WQkFNTVNXVmphRzh0YzIxdmEyVXQKWTI5dFltbHVaV1F0YkdsMlpTMWpiMjFpYVc1bFpDMHlNREkyTURjeU56STVNREF3TUMxbFkyaHZMVzl3WlhKaApkRzl5SUhkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNlCkZnZGNXdUgzWmU0S2NiL3RqVDZxMElTTmFTdFJJaEdpLzZMWm1JVENmNVZuM20wR2tvNEkyNmI2OTdvdUE5Tk0KSFRNaS9sUG9kbGQxWnNFYWt1cXJDSEpjNSs0Q3g5THVhVDNjUklFZXNVaDV0ZUxabThmL284L2lFQUtjYzI3bQpuSzU3MEtaRll1QW4zWmFrZUp2RlNqVUI2UDFuZE5oS212SnBkN0VzMWRhWTR4bUFqQkVZTnh0WHpWUjZOQU90CldEN0lwUmVhMXduSVZLNzFZR25IU0pNNmZkcDBCcDlWaWZCSjFiZHllY1h3ZDZzRjVTeDh0eFEwYWhsRkljNjYKUVFCU1hpTnhubE1sVWpKRERqNEpUOXVFSitqZ1kvUmhyb0doZWNhM3JzaCtxNnZpSEx1K1ZlMWk3ZmtETnROaQplWHRoMWJQTmtzTXpaSjl5djBNaEFnTUJBQUdqUlRCRE1CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXdEZ1lEClZSMFBBUUgvQkFRREFnRUdNQjBHQTFVZERnUVdCQlRzVU5jUVUwMUs5SUtWQ1BYV3JMWjZtWVdFYVRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFDVVdYZXRvMGJqeDRzNXlveFl4cmFTUktqR2NxUDNaVGZicmxTenRIN0t0bgpqbTlPaHF4VmtjTmRJTVRWUjNTcmpzZEg2MjkxZUFvSkxFS0xPSHByem1zS3JrZWdCbkZDck9MOVE5cmI0aVoyClVuQXRKa2ZuVnhEbzRIYkpxYjNlKzZpUDVRSm11MGkrcE0wTzRjdG1kVVFRVEZVSkZZU09raTIwYmtRQUxMaFkKaDZhb0RlV0UyWlJWWEc4RWhtcm9OUyt3TkxCZHJqYlV2Y3orV3lad0t0V1p1YnpSVUkzUm5MWlBScDRySnNGNgp6My80TzcyNHNXSjR5Zlh2a24weDZyS1B4dGZmemloZ0NvRnNoa0ZmbEhXSjYzdVBVd1dSYUE0MjBiQ0dZT0pGCndHSGtBK09BMGpGYzBBazhlYm52SldYcWpMT0YyUU85T3ZTaHAzdEUyUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: echo-smoke-combined-live-combined-20260727290000-echo-operator
        namespace: echo-smoke-combined-live-combined-20260727290000
        path: /mutate/echo.example.com
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: echo-operator.echo-smoke-combined-live-combined-20260727290000.echo.example.com
    namespaceSelector: {}
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - example.com
      apiVersions:
      - v1alpha1
      - v1alpha2
      operations:
      - CREATE
      - UPDATE
      resources:
      - echoresources
      scope: Namespaced
    sideEffects: None
    timeoutSeconds: 10
kind: List
metadata:
  resourceVersion: ""
