apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.2.23
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: echo-smoke-combined-live-combined-20260727243000-echo-oper5tftc
      namespace: echo-smoke-combined-live-combined-20260727243000
      uid: 2597600d-6fa7-42f9-9c68-108c58fefb96
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-27T15:16:06Z"
    creationTimestamp: "2026-07-27T15:15:40Z"
    generateName: echo-smoke-combined-live-combined-20260727243000-echo-operator-
    generation: 7
    labels:
      app.kubernetes.io/instance: echo-smoke-combined-live-combined-20260727243000
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: echo-operator
      app.kubernetes.io/version: 0.1.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: echo-operator-0.1.0
      kubernetes.io/service-name: echo-smoke-combined-live-combined-20260727243000-echo-operator
    name: echo-smoke-combined-live-combined-20260727243000-echo-operj76z7
    namespace: echo-smoke-combined-live-combined-20260727243000
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: echo-smoke-combined-live-combined-20260727243000-echo-operator
      uid: f3a49f2a-6bdd-4849-ad29-b1f072e713c2
    resourceVersion: "2228167"
    uid: 7bfcb9ca-3a97-4c2a-bb08-0dd5564bf2fe
  ports:
  - name: webhook
    port: 8443
    protocol: TCP
  - name: metrics
    port: 8080
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
