apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: "2026-07-27T15:04:15Z"
  generation: 1
  name: echo-operator.echo-smoke-combined-live-combined-20260727234000.echo.example.com
  resourceVersion: "2226026"
  uid: ef4c2417-4fa1-45f0-8883-ed1cb2a63ca6
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lVYXo4NXBsUFR0Yit4bmZMeElFQTFJVWNFVWR3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1ZERlNNRkFHQTFVRUF3eEpaV05vYnkxemJXOXJaUzFqYjIxaWFXNWxaQzFzYVhabExXTnZiV0pwYm1WawpMVEl3TWpZd056STNNak0wTURBd0xXVmphRzh0YjNCbGNtRjBiM0lnZDJWaWFHOXZheUJEUVRBZUZ3MHlOakEzCk1qY3hOVEEwTVRSYUZ3MHlOekEzTWpjeE5UQTBNVFJhTUZReFVqQlFCZ05WQkFNTVNXVmphRzh0YzIxdmEyVXQKWTI5dFltbHVaV1F0YkdsMlpTMWpiMjFpYVc1bFpDMHlNREkyTURjeU56SXpOREF3TUMxbFkyaHZMVzl3WlhKaApkRzl5SUhkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURtCitNeXVLZFNMLzYyczBSVVIvSFZZN1RZRHhieGJ2NUNQMGlYZFhxNlZ6aUQ3YUxhU1Y0VlR1ZnUwcE5KbldybHMKZWkvV09Md3VRc2hTbGR5TGtFeEpmMkpRMUNVTi9Qdlhta3pWeXVkanovY2RTOG1SRDZ3Q3I4eWdNWU0yVHVlbgp1SE5jUTNucVNSQnlNM2dXdXR6OXUxVm02WW85TUp3Qk8vUklwM0VESmJvVGxPdzRYMmY3SlY3NmQ4L1kxaHkrCkwxSTlnbzNIdHk3cU5md0YxVDdOQVN2NDBXSGxJbnkwdVBYa29VZW1zdWFpU1FxSGtyR1JodXMrK29VTkd2K3cKTHFiR0pnUkFYZk05MWJIOWd2ZVpCVGtwdDlKVG1qTzhndzRUejgxM0ExaC9OaVAvTjMvRCsvaEFzNDQvOG96ZgpKWE9wUDI1eWF5TUlJNlMrRVdvaEFnTUJBQUdqUlRCRE1CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXdEZ1lEClZSMFBBUUgvQkFRREFnRUdNQjBHQTFVZERnUVdCQlNIc2FPd0N1VVZSZHllZWpNc29nZlkzS3pPTVRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFsMitjQkFhWGFyeG0vUVZDcGplR09teDZ2c01HOTl3TWE3azJCVWdGeHdvMQpuQ0p0M1d4dlNWdVAvSm51UE9pQmxSYWRWUE83SjVtV2lYNXgxb3NodXE3aVo4UmlQdU8zR2txSEkzLzhPTU4vCjBxUlpJblc2bmFKeFpzMy90d25wc1RrZFozNUJpY3dSVVR5TjNPYkhCRDdBQlRZS3RhZGxhanNZYVAvOWZXalcKTXcrRm9WNERRcTUxY0d3UzVWK2dUd1BCeERzZkhndlhsUTFzYm1lNGloWS9xeFNVWTcxNDNQUzU4VS8yK0wyUwpEOVI2SlpFSW1TL04vMUc4Sjdzc2w5WkhHekV4REc1VGNvRlF2MXdaRDVZeGROQkg2UWhNUGdiWGgzMTh1YkxJCnlXR09IeHVuR3M2UHd2bzFTbXp5dThXLzRBMUlMK3lZUlBTd3ZPemZYZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: echo-smoke-combined-live-combined-20260727234000-echo-operator
      namespace: echo-smoke-combined-live-combined-20260727234000
      path: /validate/echo.example.com
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: echo-operator.echo-smoke-combined-live-combined-20260727234000.echo.example.com
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - example.com
    apiVersions:
    - v1alpha1
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - echoresources
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10
