apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.2.13
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: echo-smoke-combined-live-combined-20260727234000-echo-operfq9vq
      namespace: echo-smoke-combined-live-combined-20260727234000
      uid: 2a2768f3-c29b-41da-b607-a3e1b3136574
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-27T15:04:38Z"
    creationTimestamp: "2026-07-27T15:04:09Z"
    generateName: echo-smoke-combined-live-combined-20260727234000-echo-operator-
    generation: 7
    labels:
      app.kubernetes.io/instance: echo-smoke-combined-live-combined-20260727234000
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: echo-operator
      app.kubernetes.io/version: 0.1.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: echo-operator-0.1.0
      kubernetes.io/service-name: echo-smoke-combined-live-combined-20260727234000-echo-operator
    name: echo-smoke-combined-live-combined-20260727234000-echo-oper5lvm5
    namespace: echo-smoke-combined-live-combined-20260727234000
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: echo-smoke-combined-live-combined-20260727234000-echo-operator
      uid: 047fdaae-735d-4140-90b3-8a20ef5f22ba
    resourceVersion: "2226122"
    uid: aa7494a6-4fc3-4e03-9fbc-ebc317d6afc4
  ports:
  - name: webhook
    port: 8443
    protocol: TCP
  - name: metrics
    port: 8080
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
