apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.2.25
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: echo-smoke-combined-live-combined-20260727245000-echo-opergpx7m
      namespace: echo-smoke-combined-live-combined-20260727245000
      uid: 55909903-6a59-4933-b6c5-bdf34e3cf8bb
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-27T15:23:59Z"
    creationTimestamp: "2026-07-27T15:23:34Z"
    generateName: echo-smoke-combined-live-combined-20260727245000-echo-operator-
    generation: 7
    labels:
      app.kubernetes.io/instance: echo-smoke-combined-live-combined-20260727245000
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: echo-operator
      app.kubernetes.io/version: 0.1.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: echo-operator-0.1.0
      kubernetes.io/service-name: echo-smoke-combined-live-combined-20260727245000-echo-operator
    name: echo-smoke-combined-live-combined-20260727245000-echo-operg6dwq
    namespace: echo-smoke-combined-live-combined-20260727245000
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: echo-smoke-combined-live-combined-20260727245000-echo-operator
      uid: 2d3531dc-35f5-4aed-b081-978aa259df44
    resourceVersion: "2229244"
    uid: 1b04c4d0-91e8-4018-b9c4-4243fd6ac68e
  ports:
  - name: webhook
    port: 8443
    protocol: TCP
  - name: metrics
    port: 8080
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
