apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.2.37
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: echo-smoke-combined-live-combined-20260727251000-echo-operg9q75
      namespace: echo-smoke-combined-live-combined-20260727251000
      uid: ce0956ba-fd4c-4a84-a88d-3c7a69e0c633
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-27T15:31:37Z"
    creationTimestamp: "2026-07-27T15:31:11Z"
    generateName: echo-smoke-combined-live-combined-20260727251000-echo-operator-
    generation: 7
    labels:
      app.kubernetes.io/instance: echo-smoke-combined-live-combined-20260727251000
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: echo-operator
      app.kubernetes.io/version: 0.1.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: echo-operator-0.1.0
      kubernetes.io/service-name: echo-smoke-combined-live-combined-20260727251000-echo-operator
    name: echo-smoke-combined-live-combined-20260727251000-echo-operx5m28
    namespace: echo-smoke-combined-live-combined-20260727251000
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: echo-smoke-combined-live-combined-20260727251000-echo-operator
      uid: fe009806-d871-498d-9597-6357342d5cbc
    resourceVersion: "2230820"
    uid: 4f1e6c25-3df5-4e08-a9cf-528f9960bb61
  ports:
  - name: webhook
    port: 8443
    protocol: TCP
  - name: metrics
    port: 8080
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
