apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.2.55
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: echo-smoke-combined-live-combined-20260727270000-echo-operbf6gh
      namespace: echo-smoke-combined-live-combined-20260727270000
      uid: 30a8d681-6dea-4c4e-a50a-af786d73b7ba
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-27T15:49:41Z"
    creationTimestamp: "2026-07-27T15:49:15Z"
    generateName: echo-smoke-combined-live-combined-20260727270000-echo-operator-
    generation: 7
    labels:
      app.kubernetes.io/instance: echo-smoke-combined-live-combined-20260727270000
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: echo-operator
      app.kubernetes.io/version: 0.1.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: echo-operator-0.1.0
      kubernetes.io/service-name: echo-smoke-combined-live-combined-20260727270000-echo-operator
    name: echo-smoke-combined-live-combined-20260727270000-echo-operwgkh6
    namespace: echo-smoke-combined-live-combined-20260727270000
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: echo-smoke-combined-live-combined-20260727270000-echo-operator
      uid: 6d6175dd-b594-4602-864f-0514506cc770
    resourceVersion: "2234052"
    uid: 9ba14a14-da9e-4172-8f63-f7ab7fd41f3f
  ports:
  - name: webhook
    port: 8443
    protocol: TCP
  - name: metrics
    port: 8080
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
