apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: "2026-07-27T15:13:28Z"
  generation: 1
  name: echo-operator.echo-smoke-combined-live-combined-20260727242000.echo.example.com
  resourceVersion: "2227659"
  uid: fbd6b5fa-b8ea-4b76-9309-c31e77cfe9dd
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURmRENDQW1TZ0F3SUJBZ0lWQVBLVEpHcjVFUnlvRS9nVWl5SXFJRmJXeHNlYU1BMEdDU3FHU0liM0RRRUIKQ3dVQU1GUXhVakJRQmdOVkJBTU1TV1ZqYUc4dGMyMXZhMlV0WTI5dFltbHVaV1F0YkdsMlpTMWpiMjFpYVc1bApaQzB5TURJMk1EY3lOekkwTWpBd01DMWxZMmh2TFc5d1pYSmhkRzl5SUhkbFltaHZiMnNnUTBFd0hoY05Nall3Ck56STNNVFV4TXpJM1doY05NamN3TnpJM01UVXhNekkzV2pCVU1WSXdVQVlEVlFRRERFbGxZMmh2TFhOdGIydGwKTFdOdmJXSnBibVZrTFd4cGRtVXRZMjl0WW1sdVpXUXRNakF5TmpBM01qY3lOREl3TURBdFpXTm9ieTF2Y0dWeQpZWFJ2Y2lCM1pXSm9iMjlySUVOQk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnVubXRDZnFJR3p0cVV6RktodnMxRkoxT2xlMHN2dHZJU2dDK1FCcVRLR1pQNTU4K21UUStVM1VPcWxCQlpPUncKUEdZemJRNEFuRml0N0lVdGFJdHNOeXZjekdOY2x4dFpNbmJXUUlPSHVzaHE4L09DNjFUaHB5RnNXYW55blpKUwpFeFA5eS9tbU41UFo1RVhHeDlaWWxsemRNM3AxclFDZitwc1hKaHphaTZONG5LMWpoODZZM3VVUFY5MUd2cm1qCkVQRzdhZExkN3pFM1BoaElsK0hET3BhMXF2aHhzcCtMTDU1bm8yMWtBeG1oa1VFaXNGVGtMSEZpaElVQWlKb2gKWElaSk8vS2hRbENMNDlRWkNZT2N1V1VudTZjU1daei9OclNCajBZa2EvU3dGMUM1VGtUWUN5SGdsRkdhVmdqRgpNVk10ZTFxODRJNGxmYnMxQW5maDdRSURBUUFCbzBVd1F6QVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQTRHCkExVWREd0VCL3dRRUF3SUJCakFkQmdOVkhRNEVGZ1FVM3JPU2FQV1poMEdiWEllQUNheFhjVHY3cnk0d0RRWUoKS29aSWh2Y05BUUVMQlFBRGdnRUJBRWZ3TmtWTW0yajVTdzhQRndhNVZ3QWFnVklrUUtRdEg3VnZ2aUZXYmlWSwpoNzdiRXArNTVXZWxWSC9IUHM0NzhEbFhJSmN6ZlhHR2RYNjZiUFcvcGc5NjBrMGIwTnZFdnFySEp4TXZJZTg5ClcvYWpyM2NQWTdNMitRdUwrTTB1N2g0WVpQRitiQStSeHQ5WTE1cks0SzJQdmlrYUZ1Z2ppd090alJHemNEYmcKaXMyRXE3WU1zSE9rR1daUTI3SDFaeWJ5OHFlOWlOV21ZK2hWMDlVUHo1WC9laVdoMVVVSmVpeXp3K0tQM21OaQpIMXdEZDlTamZjRjZOdmVpekNlMjRyTEpDVGNFRHZIVkZCY25VNzhaWEFCR3grenljQVhRcTlXQ3JtelFVL2oyClVKamdQN3ptS2c2U0dDQWlSZnNpd1J0UndlVVhHNjM3YTBMWDdLdFM0a2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: echo-smoke-combined-live-combined-20260727242000-echo-operator
      namespace: echo-smoke-combined-live-combined-20260727242000
      path: /validate/echo.example.com
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: echo-operator.echo-smoke-combined-live-combined-20260727242000.echo.example.com
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - example.com
    apiVersions:
    - v1alpha1
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - echoresources
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10
