apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.1.2.21
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: echo-smoke-combined-live-combined-20260727242000-echo-oper5pmnb
      namespace: echo-smoke-combined-live-combined-20260727242000
      uid: 756610b9-a6b0-40ce-9d72-4e2a013fb760
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-27T15:13:47Z"
    creationTimestamp: "2026-07-27T15:13:22Z"
    generateName: echo-smoke-combined-live-combined-20260727242000-echo-operator-
    generation: 7
    labels:
      app.kubernetes.io/instance: echo-smoke-combined-live-combined-20260727242000
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: echo-operator
      app.kubernetes.io/version: 0.1.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: echo-operator-0.1.0
      kubernetes.io/service-name: echo-smoke-combined-live-combined-20260727242000-echo-operator
    name: echo-smoke-combined-live-combined-20260727242000-echo-operd8j6n
    namespace: echo-smoke-combined-live-combined-20260727242000
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: echo-smoke-combined-live-combined-20260727242000-echo-operator
      uid: d0c580e3-d0a1-4e39-b970-3dc324ffeac7
    resourceVersion: "2227759"
    uid: 6c2fb442-1f42-4cc1-a0a0-88794644e6fe
  ports:
  - name: webhook
    port: 8443
    protocol: TCP
  - name: metrics
    port: 8080
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
